### ISSUE TITLE
Code highlighter is broken

### ISSUE THREAD

**Issue by tempfirstuser** [laminas/documentation-theme#4] opened 2020-01-03 07:41 UTC
https://docs.laminas.dev/laminas-modulemanager/module-class/#a-typical-module-class

**Comment by tempfirstuser** [comment] 2020-01-03 07:45
It's duplicate of https://github.com/laminas/documentation-theme/issues/3

**Comment by weierophinney** [comment] 2020-01-03 15:30
Duplicate of #3

**Closed by weierophinney** 2020-01-03 15:30 UTC
